//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestClient.SmartCollabRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmartCollabRef.DataFilterSoap")]
    public interface DataFilterSoap {
        
        // CODEGEN: Generating message contract since element name keyword from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchService", ReplyAction="*")]
        TestClient.SmartCollabRef.searchServiceResponse searchService(TestClient.SmartCollabRef.searchServiceRequest request);
        
        // CODEGEN: Generating message contract since element name keyword from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchRequirement", ReplyAction="*")]
        TestClient.SmartCollabRef.searchRequirementResponse searchRequirement(TestClient.SmartCollabRef.searchRequirementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/republishService", ReplyAction="*")]
        int republishService(int service_id, int tenant_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/unpublish_service", ReplyAction="*")]
        int unpublish_service(int service_id, int tenant_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/unpublishReq", ReplyAction="*")]
        int unpublishReq(int tenant_id, int req_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getRequirementsOwner", ReplyAction="*")]
        int getRequirementsOwner(int req_id);
        
        // CODEGEN: Generating message contract since element name serviceURL from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/publishMyService", ReplyAction="*")]
        TestClient.SmartCollabRef.publishMyServiceResponse publishMyService(TestClient.SmartCollabRef.publishMyServiceRequest request);
        
        // CODEGEN: Generating message contract since element name getOwnedServiceListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getOwnedServiceList", ReplyAction="*")]
        TestClient.SmartCollabRef.getOwnedServiceListResponse getOwnedServiceList(TestClient.SmartCollabRef.getOwnedServiceListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/bindService", ReplyAction="*")]
        int bindService(int service_id, int tenant_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/bindRequirment", ReplyAction="*")]
        int bindRequirment(int req_id, int tenant_id);
        
        // CODEGEN: Generating message contract since element name getServiceSubscriberResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getServiceSubscriber", ReplyAction="*")]
        TestClient.SmartCollabRef.getServiceSubscriberResponse getServiceSubscriber(TestClient.SmartCollabRef.getServiceSubscriberRequest request);
        
        // CODEGEN: Generating message contract since element name getRequirementSubscriberResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getRequirementSubscriber", ReplyAction="*")]
        TestClient.SmartCollabRef.getRequirementSubscriberResponse getRequirementSubscriber(TestClient.SmartCollabRef.getRequirementSubscriberRequest request);
        
        // CODEGEN: Generating message contract since element name description from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/publishMyRequirements", ReplyAction="*")]
        TestClient.SmartCollabRef.publishMyRequirementsResponse publishMyRequirements(TestClient.SmartCollabRef.publishMyRequirementsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchService", Namespace="http://tempuri.org/", Order=0)]
        public TestClient.SmartCollabRef.searchServiceRequestBody Body;
        
        public searchServiceRequest() {
        }
        
        public searchServiceRequest(TestClient.SmartCollabRef.searchServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class searchServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string keyword;
        
        public searchServiceRequestBody() {
        }
        
        public searchServiceRequestBody(string keyword) {
            this.keyword = keyword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchServiceResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestClient.SmartCollabRef.searchServiceResponseBody Body;
        
        public searchServiceResponse() {
        }
        
        public searchServiceResponse(TestClient.SmartCollabRef.searchServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class searchServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string searchServiceResult;
        
        public searchServiceResponseBody() {
        }
        
        public searchServiceResponseBody(string searchServiceResult) {
            this.searchServiceResult = searchServiceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchRequirementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchRequirement", Namespace="http://tempuri.org/", Order=0)]
        public TestClient.SmartCollabRef.searchRequirementRequestBody Body;
        
        public searchRequirementRequest() {
        }
        
        public searchRequirementRequest(TestClient.SmartCollabRef.searchRequirementRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class searchRequirementRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string keyword;
        
        public searchRequirementRequestBody() {
        }
        
        public searchRequirementRequestBody(string keyword) {
            this.keyword = keyword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchRequirementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchRequirementResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestClient.SmartCollabRef.searchRequirementResponseBody Body;
        
        public searchRequirementResponse() {
        }
        
        public searchRequirementResponse(TestClient.SmartCollabRef.searchRequirementResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class searchRequirementResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string searchRequirementResult;
        
        public searchRequirementResponseBody() {
        }
        
        public searchRequirementResponseBody(string searchRequirementResult) {
            this.searchRequirementResult = searchRequirementResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishMyServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="publishMyService", Namespace="http://tempuri.org/", Order=0)]
        public TestClient.SmartCollabRef.publishMyServiceRequestBody Body;
        
        public publishMyServiceRequest() {
        }
        
        public publishMyServiceRequest(TestClient.SmartCollabRef.publishMyServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class publishMyServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int tenant_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string serviceURL;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string description;
        
        public publishMyServiceRequestBody() {
        }
        
        public publishMyServiceRequestBody(int tenant_id, string serviceURL, string description) {
            this.tenant_id = tenant_id;
            this.serviceURL = serviceURL;
            this.description = description;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishMyServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="publishMyServiceResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestClient.SmartCollabRef.publishMyServiceResponseBody Body;
        
        public publishMyServiceResponse() {
        }
        
        public publishMyServiceResponse(TestClient.SmartCollabRef.publishMyServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class publishMyServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int publishMyServiceResult;
        
        public publishMyServiceResponseBody() {
        }
        
        public publishMyServiceResponseBody(int publishMyServiceResult) {
            this.publishMyServiceResult = publishMyServiceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOwnedServiceListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOwnedServiceList", Namespace="http://tempuri.org/", Order=0)]
        public TestClient.SmartCollabRef.getOwnedServiceListRequestBody Body;
        
        public getOwnedServiceListRequest() {
        }
        
        public getOwnedServiceListRequest(TestClient.SmartCollabRef.getOwnedServiceListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getOwnedServiceListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int tenant_id;
        
        public getOwnedServiceListRequestBody() {
        }
        
        public getOwnedServiceListRequestBody(int tenant_id) {
            this.tenant_id = tenant_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOwnedServiceListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOwnedServiceListResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestClient.SmartCollabRef.getOwnedServiceListResponseBody Body;
        
        public getOwnedServiceListResponse() {
        }
        
        public getOwnedServiceListResponse(TestClient.SmartCollabRef.getOwnedServiceListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getOwnedServiceListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestClient.SmartCollabRef.ArrayOfAnyType getOwnedServiceListResult;
        
        public getOwnedServiceListResponseBody() {
        }
        
        public getOwnedServiceListResponseBody(TestClient.SmartCollabRef.ArrayOfAnyType getOwnedServiceListResult) {
            this.getOwnedServiceListResult = getOwnedServiceListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getServiceSubscriberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getServiceSubscriber", Namespace="http://tempuri.org/", Order=0)]
        public TestClient.SmartCollabRef.getServiceSubscriberRequestBody Body;
        
        public getServiceSubscriberRequest() {
        }
        
        public getServiceSubscriberRequest(TestClient.SmartCollabRef.getServiceSubscriberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getServiceSubscriberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int service_id;
        
        public getServiceSubscriberRequestBody() {
        }
        
        public getServiceSubscriberRequestBody(int service_id) {
            this.service_id = service_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getServiceSubscriberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getServiceSubscriberResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestClient.SmartCollabRef.getServiceSubscriberResponseBody Body;
        
        public getServiceSubscriberResponse() {
        }
        
        public getServiceSubscriberResponse(TestClient.SmartCollabRef.getServiceSubscriberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getServiceSubscriberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestClient.SmartCollabRef.ArrayOfAnyType getServiceSubscriberResult;
        
        public getServiceSubscriberResponseBody() {
        }
        
        public getServiceSubscriberResponseBody(TestClient.SmartCollabRef.ArrayOfAnyType getServiceSubscriberResult) {
            this.getServiceSubscriberResult = getServiceSubscriberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRequirementSubscriberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRequirementSubscriber", Namespace="http://tempuri.org/", Order=0)]
        public TestClient.SmartCollabRef.getRequirementSubscriberRequestBody Body;
        
        public getRequirementSubscriberRequest() {
        }
        
        public getRequirementSubscriberRequest(TestClient.SmartCollabRef.getRequirementSubscriberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getRequirementSubscriberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int req_id;
        
        public getRequirementSubscriberRequestBody() {
        }
        
        public getRequirementSubscriberRequestBody(int req_id) {
            this.req_id = req_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRequirementSubscriberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRequirementSubscriberResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestClient.SmartCollabRef.getRequirementSubscriberResponseBody Body;
        
        public getRequirementSubscriberResponse() {
        }
        
        public getRequirementSubscriberResponse(TestClient.SmartCollabRef.getRequirementSubscriberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getRequirementSubscriberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestClient.SmartCollabRef.ArrayOfAnyType getRequirementSubscriberResult;
        
        public getRequirementSubscriberResponseBody() {
        }
        
        public getRequirementSubscriberResponseBody(TestClient.SmartCollabRef.ArrayOfAnyType getRequirementSubscriberResult) {
            this.getRequirementSubscriberResult = getRequirementSubscriberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishMyRequirementsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="publishMyRequirements", Namespace="http://tempuri.org/", Order=0)]
        public TestClient.SmartCollabRef.publishMyRequirementsRequestBody Body;
        
        public publishMyRequirementsRequest() {
        }
        
        public publishMyRequirementsRequest(TestClient.SmartCollabRef.publishMyRequirementsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class publishMyRequirementsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int tenant_id;
        
        public publishMyRequirementsRequestBody() {
        }
        
        public publishMyRequirementsRequestBody(string description, int tenant_id) {
            this.description = description;
            this.tenant_id = tenant_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishMyRequirementsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="publishMyRequirementsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestClient.SmartCollabRef.publishMyRequirementsResponseBody Body;
        
        public publishMyRequirementsResponse() {
        }
        
        public publishMyRequirementsResponse(TestClient.SmartCollabRef.publishMyRequirementsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class publishMyRequirementsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int publishMyRequirementsResult;
        
        public publishMyRequirementsResponseBody() {
        }
        
        public publishMyRequirementsResponseBody(int publishMyRequirementsResult) {
            this.publishMyRequirementsResult = publishMyRequirementsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataFilterSoapChannel : TestClient.SmartCollabRef.DataFilterSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataFilterSoapClient : System.ServiceModel.ClientBase<TestClient.SmartCollabRef.DataFilterSoap>, TestClient.SmartCollabRef.DataFilterSoap {
        
        public DataFilterSoapClient() {
        }
        
        public DataFilterSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataFilterSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataFilterSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataFilterSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestClient.SmartCollabRef.searchServiceResponse TestClient.SmartCollabRef.DataFilterSoap.searchService(TestClient.SmartCollabRef.searchServiceRequest request) {
            return base.Channel.searchService(request);
        }
        
        public string searchService(string keyword) {
            TestClient.SmartCollabRef.searchServiceRequest inValue = new TestClient.SmartCollabRef.searchServiceRequest();
            inValue.Body = new TestClient.SmartCollabRef.searchServiceRequestBody();
            inValue.Body.keyword = keyword;
            TestClient.SmartCollabRef.searchServiceResponse retVal = ((TestClient.SmartCollabRef.DataFilterSoap)(this)).searchService(inValue);
            return retVal.Body.searchServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestClient.SmartCollabRef.searchRequirementResponse TestClient.SmartCollabRef.DataFilterSoap.searchRequirement(TestClient.SmartCollabRef.searchRequirementRequest request) {
            return base.Channel.searchRequirement(request);
        }
        
        public string searchRequirement(string keyword) {
            TestClient.SmartCollabRef.searchRequirementRequest inValue = new TestClient.SmartCollabRef.searchRequirementRequest();
            inValue.Body = new TestClient.SmartCollabRef.searchRequirementRequestBody();
            inValue.Body.keyword = keyword;
            TestClient.SmartCollabRef.searchRequirementResponse retVal = ((TestClient.SmartCollabRef.DataFilterSoap)(this)).searchRequirement(inValue);
            return retVal.Body.searchRequirementResult;
        }
        
        public int republishService(int service_id, int tenant_id) {
            return base.Channel.republishService(service_id, tenant_id);
        }
        
        public int unpublish_service(int service_id, int tenant_id) {
            return base.Channel.unpublish_service(service_id, tenant_id);
        }
        
        public int unpublishReq(int tenant_id, int req_id) {
            return base.Channel.unpublishReq(tenant_id, req_id);
        }
        
        public int getRequirementsOwner(int req_id) {
            return base.Channel.getRequirementsOwner(req_id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestClient.SmartCollabRef.publishMyServiceResponse TestClient.SmartCollabRef.DataFilterSoap.publishMyService(TestClient.SmartCollabRef.publishMyServiceRequest request) {
            return base.Channel.publishMyService(request);
        }
        
        public int publishMyService(int tenant_id, string serviceURL, string description) {
            TestClient.SmartCollabRef.publishMyServiceRequest inValue = new TestClient.SmartCollabRef.publishMyServiceRequest();
            inValue.Body = new TestClient.SmartCollabRef.publishMyServiceRequestBody();
            inValue.Body.tenant_id = tenant_id;
            inValue.Body.serviceURL = serviceURL;
            inValue.Body.description = description;
            TestClient.SmartCollabRef.publishMyServiceResponse retVal = ((TestClient.SmartCollabRef.DataFilterSoap)(this)).publishMyService(inValue);
            return retVal.Body.publishMyServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestClient.SmartCollabRef.getOwnedServiceListResponse TestClient.SmartCollabRef.DataFilterSoap.getOwnedServiceList(TestClient.SmartCollabRef.getOwnedServiceListRequest request) {
            return base.Channel.getOwnedServiceList(request);
        }
        
        public TestClient.SmartCollabRef.ArrayOfAnyType getOwnedServiceList(int tenant_id) {
            TestClient.SmartCollabRef.getOwnedServiceListRequest inValue = new TestClient.SmartCollabRef.getOwnedServiceListRequest();
            inValue.Body = new TestClient.SmartCollabRef.getOwnedServiceListRequestBody();
            inValue.Body.tenant_id = tenant_id;
            TestClient.SmartCollabRef.getOwnedServiceListResponse retVal = ((TestClient.SmartCollabRef.DataFilterSoap)(this)).getOwnedServiceList(inValue);
            return retVal.Body.getOwnedServiceListResult;
        }
        
        public int bindService(int service_id, int tenant_id) {
            return base.Channel.bindService(service_id, tenant_id);
        }
        
        public int bindRequirment(int req_id, int tenant_id) {
            return base.Channel.bindRequirment(req_id, tenant_id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestClient.SmartCollabRef.getServiceSubscriberResponse TestClient.SmartCollabRef.DataFilterSoap.getServiceSubscriber(TestClient.SmartCollabRef.getServiceSubscriberRequest request) {
            return base.Channel.getServiceSubscriber(request);
        }
        
        public TestClient.SmartCollabRef.ArrayOfAnyType getServiceSubscriber(int service_id) {
            TestClient.SmartCollabRef.getServiceSubscriberRequest inValue = new TestClient.SmartCollabRef.getServiceSubscriberRequest();
            inValue.Body = new TestClient.SmartCollabRef.getServiceSubscriberRequestBody();
            inValue.Body.service_id = service_id;
            TestClient.SmartCollabRef.getServiceSubscriberResponse retVal = ((TestClient.SmartCollabRef.DataFilterSoap)(this)).getServiceSubscriber(inValue);
            return retVal.Body.getServiceSubscriberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestClient.SmartCollabRef.getRequirementSubscriberResponse TestClient.SmartCollabRef.DataFilterSoap.getRequirementSubscriber(TestClient.SmartCollabRef.getRequirementSubscriberRequest request) {
            return base.Channel.getRequirementSubscriber(request);
        }
        
        public TestClient.SmartCollabRef.ArrayOfAnyType getRequirementSubscriber(int req_id) {
            TestClient.SmartCollabRef.getRequirementSubscriberRequest inValue = new TestClient.SmartCollabRef.getRequirementSubscriberRequest();
            inValue.Body = new TestClient.SmartCollabRef.getRequirementSubscriberRequestBody();
            inValue.Body.req_id = req_id;
            TestClient.SmartCollabRef.getRequirementSubscriberResponse retVal = ((TestClient.SmartCollabRef.DataFilterSoap)(this)).getRequirementSubscriber(inValue);
            return retVal.Body.getRequirementSubscriberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestClient.SmartCollabRef.publishMyRequirementsResponse TestClient.SmartCollabRef.DataFilterSoap.publishMyRequirements(TestClient.SmartCollabRef.publishMyRequirementsRequest request) {
            return base.Channel.publishMyRequirements(request);
        }
        
        public int publishMyRequirements(string description, int tenant_id) {
            TestClient.SmartCollabRef.publishMyRequirementsRequest inValue = new TestClient.SmartCollabRef.publishMyRequirementsRequest();
            inValue.Body = new TestClient.SmartCollabRef.publishMyRequirementsRequestBody();
            inValue.Body.description = description;
            inValue.Body.tenant_id = tenant_id;
            TestClient.SmartCollabRef.publishMyRequirementsResponse retVal = ((TestClient.SmartCollabRef.DataFilterSoap)(this)).publishMyRequirements(inValue);
            return retVal.Body.publishMyRequirementsResult;
        }
    }
}
